name: Check pull request source branch

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || inputs.pr_number || github.ref }}
  cancel-in-progress: true

jobs:
  check-pr-source-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Check branches
        run: |
          head="${{ github.head_ref }}"
          base="${{ github.base_ref }}"
          if [ "$base" == "13.0" ]; then
            if [ "$head" != "18.0-release" ] && [[ "$head" != *-hotfix ]]; then
              echo "Merge requests to the 13.0 branch are only allowed from the 18.0-release branch or a hotfix branch (e.g. fix-something-hotfix)."
              exit 1
            fi
          fi